pages/urls.py
"""Defines URL patterns for pages."""

from django.urls import path
from . import views

urlpatterns = [
    # Home page
    path('', views.home, name='home'),
    path('violations', views.violations, name='violations'),
    path('purifier', views.purifier, name='purifier'),
    path('events', views.events, name='events'),

]

seaq/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pages.urls','pages'), namespace='pages')),
]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    """The home page for seaq"""
    return render(request, 'pages/home.html')

def violations(request):
    return render(request, 'pages/violations.html')

def purifier(request):
    return render(request, 'pages/purifier.html')

def events(request):
    return render(request, 'pages/events.html')

pages/templates/pages/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>SEAQ</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'pages/images/crsd.ico' %}"/>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'pages/css/styles.css' %}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Dearborn Air Quality</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:violations' %}">AQ Violations</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:purifier' %}">Air Purifiers</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'pages:events' %}">Events</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock content %}
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            Street Address
                            <br />
                            City, State Zip Code
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <p class="lead mb-0">
                            <a href="https://southenddearborn.com">CRSD Website</a>
                        </p>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About This Template</h4>
                        <p class="lead mb-0">
                            This website uses a free to use, MIT licensed Bootstrap theme created by
                            <a href="http://startbootstrap.com">Start Bootstrap</a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; CRSD 2023</small></div>
        </div>
        {% block content2 %}{% endblock content2 %}
        <!-- bootstrap js-->
        {% bootstrap_javascript %}
        <!-- Core theme JS-->
        <script src="{% static 'pages/js/scripts.js' %}"></script>
    </body>
</html>

pages/templates/pages/events.html
{% extends "pages/base.html" %}
{% load static %}

{% block content %}

<style>

    .center-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }

        .full-width-img {
            max-width: 100%;
            height: auto;
    }
    </style>
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="{% static 'pages/images/paper.png' %}" alt="..." />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Events</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">To learn more, feel free to attend any of these events below.</p>
        </div>
    </header>
    <section class="page-section mb-0" id="new-section4">
        <div class ="center-container">
            <img class="full-width-img" src="{% static 'pages/images/flyer.png' %}" alt="Flyer Image Failed Lol">
        </div>
    </section>
{% endblock content %}

pages/templates/pages/home.html
{% extends "pages/base.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="{% static 'pages/images/co2.png' %}" alt="..." />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Dearborn Air Quality</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">Feel free to explore this website and learn about air quality and air purifiers in the Dearborn community!</p>
        </div>
    </header>
    <!-- Portfolio Section-->
    <section class="page-section portfolio" id="portfolio">
        <div class="container">
            <!-- Portfolio Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Fun Facts</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Portfolio Grid Items-->
            <div class="row justify-content-center">
                <!-- Portfolio Item 1-->
                <div class="col-md-6 col-lg-4 mb-5">
                    <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal1">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{% static 'pages/images/factory.png' %}" alt="..." />
                    </div>
                </div>
                <!-- Portfolio Item 2-->
                <div class="col-md-6 col-lg-4 mb-5">
                    <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal2">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{% static 'pages/images/tree.png' %}" alt="..." />
                    </div>
                </div>
                <!-- Portfolio Item 3-->
                <div class="col-md-6 col-lg-4 mb-5">
                    <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal3">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{% static 'pages/images/covid.png' %}" alt="..." />
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Section-->
    <section class="page-section bg-primary text-white mb-0" id="about">
        <div class="container">
            <!-- About Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- About Section Content-->
            <div class="row">
                <div class="col-lg-4 ms-auto"><p class="lead">Welcome to CRSD's Air Quality Portal! Dedicated to enhancing awareness about Dearborn's southern end air conditions, our platform offers valuable insights and resources. Here, you'll find comprehensive guides on reporting air quality violations and instructions for setting up air purifiers in your residence. Although our primary focus is the South End community, our mission is to enlighten all about the environmental challenges faced by this region.</p></div>
                <div class="col-lg-4 me-auto"><p class="lead">With your support, positive change is on the horizon. We are excited to share that air purifiers will soon be a standard feature in every South End home. Our website aims to be your go-to resource for seamless purifier installation. Dive in, discover more, and see how you can contribute to this initiative. Thank you for investing your time in our endeavor!</p></div>
            </div>
        </div>
    </section>
    <!-- Contact Section-->
    <section class="page-section" id="contact">
        <div class="container">
            <!-- Contact Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Us</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="container mt-5">
                <div class="row">
                    <div class="text-center">
                        <img src="{% static 'pages/images/crsd.jpg' %}" alt="Failed lol" class="img-fluid mb-3">
                    </div>
                    <div class="col-lg-5 mx-auto text-center">
                        <h4 class="lead">Phone Number: 313-673-3415</h4>
                        <h4 class="lead">Email: info@southendearborn.com</h4>
                    </div>                    
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block content2 %}
    <!-- Portfolio Modals-->
    <!-- Portfolio Modal 1-->
    <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" aria-labelledby="portfolioModal1" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header border-0"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
                <div class="modal-body text-center pb-5">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <!-- Portfolio Modal - Title-->
                                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Factories</h2>
                                <!-- Icon Divider-->
                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                <!-- Portfolio Modal - Image-->
                                <img class="img-fluid rounded mb-5" src="{% static 'pages/images/factory.png' %}" alt="..." />
                                <!-- Portfolio Modal - Text-->
                                <h5 class="mb-4">The South End hosts 40+ major and minor source polluting facilities.</h5>
                                <button class="btn btn-primary" data-bs-dismiss="modal">
                                    <i class="fas fa-xmark fa-fw"></i>
                                    Close Window
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Portfolio Modal 2-->
    <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" aria-labelledby="portfolioModal2" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header border-0"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
                <div class="modal-body text-center pb-5">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <!-- Portfolio Modal - Title-->
                                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Tree Coverage</h2>
                                <!-- Icon Divider-->
                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                <!-- Portfolio Modal - Image-->
                                <img class="img-fluid rounded mb-5" src="{% static 'pages/images/tree.png' %}" alt="..." />
                                <!-- Portfolio Modal - Text-->
                                <h5 class="mb-4">The South End has less than 10% of tree canopy cover compared to 70% in other parts of Dearborn and Dearborn Heights.</h5>
                                <button class="btn btn-primary" data-bs-dismiss="modal">
                                    <i class="fas fa-xmark fa-fw"></i>
                                    Close Window
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Portfolio Modal 3-->
    <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" aria-labelledby="portfolioModal3" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header border-0"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
                <div class="modal-body text-center pb-5">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <!-- Portfolio Modal - Title-->
                                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">COVID</h2>
                                <!-- Icon Divider-->
                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                <!-- Portfolio Modal - Image-->
                                <img class="img-fluid rounded mb-5" src="{% static 'pages/images/covid.png' %}" alt="..." />
                                <!-- Portfolio Modal - Text-->
                                <h5 class="mb-4">People who live in high polluted areas are 8% more likely to die from COVID-19 than others who live in a slightly less polluted area.</h5>
                                <button class="btn btn-primary" data-bs-dismiss="modal">
                                    <i class="fas fa-xmark fa-fw"></i>
                                    Close Window
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content2 %}

pages/templates/pages/purifier.html
{% extends "pages/base.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="{% static 'pages/images/purifier.png' %}" alt="..." />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Air Purifiers</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">In the next couple of months, every home in the South End will be receiving an air purifier. 
                If you live in the South End of Dearborn, here's how you can install one.</p>
        </div>
    </header>
    <style>
        .custom-list-style li {
            margin-bottom: 2rem;  /* Adjust this value as needed */
        }
    </style>
    <section class="page-section text-secondary mb-0" id="new-section">
        <div class="container">
            <!-- New Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase">How Do I Install One in My Home?</h2>
            
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            
            <!-- New Section Content -->
            <div class="row">
                <!-- I'm using col-lg-7 here to make the text wider than the previous section -->
                <div class="col-lg-7 mx-auto">
                    <ul class="lead list-unstyled text-center custom-list-style">
                        <!-- Bullet Points -->
                        <li><h4>Step 1: Install purifier</h4></li>
                        <li><h4>Step 2: Install purifier</h4></li>
                        <li><h4>Step 3: Install purifier</h4></li>
                        <li><h4>Step 4: Install purifier</h4></li>
                        <li><h4>Step 5: Install purifier</h4></li>
                        <li><h4>Step 6: You're done. Congrats.</h4></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

pages/templates/pages/violations.html
{% extends "pages/base.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="{% static 'pages/images/noco2.png' %}" alt="..." />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Air Quality Violations</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">In the South End, if you see any of these bad physical signs, they could be air violations!</p>
        </div>
    </header>
    <style>
        .custom-list-style li {
            margin-bottom: 2rem;  /* Adjust this value as needed */
        }
    </style>
    <section class="page-section text-secondary mb-0" id="new-section">
        <div class="container">
            <!-- New Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase">What are they?</h2>
            
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            
            <!-- New Section Content -->
            <div class="row">
                <!-- I'm using col-lg-7 here to make the text wider than the previous section -->
                <div class="col-lg-7 mx-auto">
                    <ul class="lead list-unstyled text-center custom-list-style">
                        <!-- Bullet Points -->
                        <li>
                            <h4>Any Unclear, Colored, Excessive Smoke</h4>
                            <p>(Can be gray or any other color and must appear from any smoke stack or property)</p>
                        </li>
                        <li><h4>Any Foul Odor Including Waste, Fire, or Chemical Smells</h4></li>
                        <li><h4>Any Developing Health Issues Such as Asthma</h4></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section bg-primary text-white mb-0" id="new-section2">
        <div class="container">
            <!-- New Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase text-white">How Do I Report Them?</h2>
            
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            
            <!-- New Section Content -->
            <div class="row">
                <!-- I'm using col-lg-7 here to make the text wider than the previous section -->
                <div class="col-lg-7 mx-auto">
                    <ul class="lead list-unstyled text-center custom-list-style">
                        <!-- Bullet Points -->
                        <li><h2>Phone:</h2></li>
                        <li><h4>Step 1: Call PEAS EGLE: (800) 292-4706</h4></li>
                        <li>
                            <h4>Step 2: State the location and description of air quality violation(s)</h4>
                            <p>(Location: South End, Dearborn and Factory Name/Location)</p>
                            <p>(Description: Bad Physical Sign(s))</p>
                        </li>
                        <div class="divider-custom divider-light">
                            <div class="divider-custom-line"></div>
                            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                            <div class="divider-custom-line"></div>
                        </div>
                        <li><h2>Online:</h2></li>
                        <li><h4>Step 1: Google Michigan Department of Air Quality</h4></li>
                        <li>
                            <h4>Step 2: Click on the link that says “Michigan Department of Air Quality<</h4>
                            <p>(Usually, it's the first link)</p>
                        </li>
                        <li><h4>Step 3: Click “Submit a Violation”</h4></li>
                        <li><h4>Step 4: Fill out and submit the form</h4></li>
                        <!-- Add more points as needed -->
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section text-secondary mb-0" id="new-section3">
        <div class="container">
            <!-- New Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase">WHy Should I Report Them?</h2>
            
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            
            <!-- New Section Content -->
            <div class="row">
                <!-- I'm using col-lg-8 here to make the text wider than the previous section -->
                <div class="col-lg-8 mx-auto text-center lead">
                    <h4>
                        On April 11, 2023, a settlement between Cleveland Cliffs Inc. and PEAS EGLE arose over air quality violations 
                        by the company. Because of this settlement, our community will receive over $250,000 in funding. The 
                        Concerned Residents of South Dearborn will manage the funding to purchase an air purifier for every home in the 
                        South End. AQ violations brought this environmental project into fruition, so reporting these violations can help 
                        your community.
                    </h4>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}